[pytest]
; пусть к папке с тестами
testpaths = tests
; говорим питону чтобы смотрил импорты с этого уровня
pythonpath = .
; пусть сам решает когда работать ассинхронно, когда синхронно
asyncio_mode = auto