"""initial schema

Revision ID: 0ad8eafc7bcb
Revises: 
Create Date: 2026-08-16 16:26:20.632802

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0ad8eafc7bcb'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('service_balance', sa.Float(), nullable=False),
    sa.Column('commission_rate', sa.Float(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=False)

    op.create_table('exchange_api_keys',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('exchange', sa.String(length=50), nullable=False),
    sa.Column('label', sa.String(length=100), nullable=False),
    sa.Column('api_key_encrypted', sa.Text(), nullable=False),
    sa.Column('api_secret_encrypted', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('exchange_api_keys', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_exchange_api_keys_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_exchange_api_keys_user_id'), ['user_id'], unique=False)

    op.create_table('payments',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bots',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('pair', sa.String(length=50), nullable=False),
    sa.Column('leverage', sa.Integer(), nullable=False),
    sa.Column('direction', sa.String(length=10), nullable=False),
    sa.Column('tradable_balance_ratio', sa.Float(), nullable=False),
    sa.Column('stake_amount', sa.Float(), nullable=False),
    sa.Column('strategy_preset', sa.String(length=20), nullable=False),
    sa.Column('entry_filters_long', sa.JSON(), nullable=False),
    sa.Column('entry_filters_short', sa.JSON(), nullable=False),
    sa.Column('take_profit', sa.JSON(), nullable=False),
    sa.Column('stop_loss', sa.Float(), nullable=False),
    sa.Column('trailing_stop', sa.Boolean(), nullable=False),
    sa.Column('trailing_config', sa.JSON(), nullable=True),
    sa.Column('dry_run', sa.Boolean(), nullable=False),
    sa.Column('api_key_id', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('total_profit', sa.Float(), nullable=False),
    sa.Column('total_commission_paid_usdt', sa.Float(), nullable=False),
    sa.Column('total_commission_paid_rub', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('container_id', sa.String(length=64), nullable=True),
    sa.Column('container_name', sa.String(length=100), nullable=False),
    sa.Column('api_port', sa.Integer(), nullable=False),
    sa.Column('api_username', sa.String(length=50), nullable=False),
    sa.Column('api_password', sa.String(length=100), nullable=False),
    sa.Column('error_message', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['api_key_id'], ['exchange_api_keys.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('bots', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_bots_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_bots_user_id'), ['user_id'], unique=False)

    op.create_table('trades',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bot_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('freqtrade_trade_id', sa.Integer(), nullable=False),
    sa.Column('pair', sa.String(length=50), nullable=False),
    sa.Column('direction', sa.String(length=10), nullable=False),
    sa.Column('open_rate', sa.Float(), nullable=False),
    sa.Column('close_rate', sa.Float(), nullable=True),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('leverage', sa.Float(), nullable=False),
    sa.Column('profit_usdt', sa.Float(), nullable=True),
    sa.Column('profit_pct', sa.Float(), nullable=True),
    sa.Column('exchange_rate_rub_usdt', sa.Float(), nullable=True),
    sa.Column('commission_usdt', sa.Float(), nullable=False),
    sa.Column('commission_rub', sa.Float(), nullable=False),
    sa.Column('commission_paid', sa.Boolean(), nullable=False),
    sa.Column('exit_reason', sa.String(length=50), nullable=True),
    sa.Column('open_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('close_time', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['bot_id'], ['bots.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('trades', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_trades_bot_id'), ['bot_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_trades_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_trades_user_id'), ['user_id'], unique=False)

    op.create_table('balance_transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('type', sa.String(length=30), nullable=False),
    sa.Column('trade_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['trade_id'], ['trades.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('balance_transactions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_balance_transactions_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_balance_transactions_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('balance_transactions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_balance_transactions_user_id'))
        batch_op.drop_index(batch_op.f('ix_balance_transactions_id'))

    op.drop_table('balance_transactions')
    with op.batch_alter_table('trades', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_trades_user_id'))
        batch_op.drop_index(batch_op.f('ix_trades_id'))
        batch_op.drop_index(batch_op.f('ix_trades_bot_id'))

    op.drop_table('trades')
    with op.batch_alter_table('bots', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_bots_user_id'))
        batch_op.drop_index(batch_op.f('ix_bots_id'))

    op.drop_table('bots')
    op.drop_table('payments')
    with op.batch_alter_table('exchange_api_keys', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_exchange_api_keys_user_id'))
        batch_op.drop_index(batch_op.f('ix_exchange_api_keys_id'))

    op.drop_table('exchange_api_keys')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))
        batch_op.drop_index(batch_op.f('ix_users_id'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    # ### end Alembic commands ###
