"""add assistant_requests for rate limit

Revision ID: 1ed2071cd8cb
Revises: 0ad8eafc7bcb
Create Date: 2026-08-21 12:54:45.684085

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1ed2071cd8cb'
down_revision: Union[str, Sequence[str], None] = '0ad8eafc7bcb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assistant_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('assistant_requests', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_assistant_requests_id'), ['id'], unique=False)
        batch_op.create_index('ix_assistant_requests_user_created', ['user_id', 'created_at'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assistant_requests', schema=None) as batch_op:
        batch_op.drop_index('ix_assistant_requests_user_created')
        batch_op.drop_index(batch_op.f('ix_assistant_requests_id'))

    op.drop_table('assistant_requests')
    # ### end Alembic commands ###
