"""add consent_log for legal consents

Revision ID: 31c2a87e9ac2
Revises: 1ed2071cd8cb
Create Date: 2026-08-26 15:30:36.797208

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '31c2a87e9ac2'
down_revision: Union[str, Sequence[str], None] = '1ed2071cd8cb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('consent_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('document_type', sa.String(length=32), nullable=False),
    sa.Column('document_version', sa.String(length=32), nullable=False),
    sa.Column('accepted_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('consent_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_consent_log_id'), ['id'], unique=False)
        batch_op.create_index('ix_consent_log_user_document', ['user_id', 'document_type'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('consent_log', schema=None) as batch_op:
        batch_op.drop_index('ix_consent_log_user_document')
        batch_op.drop_index(batch_op.f('ix_consent_log_id'))

    op.drop_table('consent_log')
    # ### end Alembic commands ###
