"""add user percent take profit and stop loss to bots

Revision ID: cdca55ee7b02
Revises: 31c2a87e9ac2
Create Date: 2026-08-27 16:02:12.142936

Проценты движения цены в том виде, в каком их задал человек. Рядом уже лежат
take_profit/stop_loss в формате freqtrade — те же числа, умноженные на плечо.

Существующие боты остаются с NULL: бэкфилл делением на плечо возможен, но
смысла в нём нет — эти боты и так торгуют по своим take_profit/stop_loss,
а интерфейс просто не покажет для них проценты.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cdca55ee7b02'
down_revision: Union[str, Sequence[str], None] = '31c2a87e9ac2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bots', schema=None) as batch_op:
        batch_op.add_column(sa.Column('take_profit_percent', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('stop_loss_percent', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bots', schema=None) as batch_op:
        batch_op.drop_column('stop_loss_percent')
        batch_op.drop_column('take_profit_percent')

    # ### end Alembic commands ###
